export enum APP_IMAGE_URLS {
  LOGO = '/images/main-logo.png',
  BANNER = '/images/banner.png',
  BROWN_CHAIR = '/images/brown-chair.png',
  WHITE_CHAIR = '/images/white-chair.png',
  SILVER_CHAIR = '/images/silver-chair.png',
  BLACK_CHAIR = '/images/black-chair.png',
  FOOTER_LOGO = '/images/footer-logo.png',
  INFO_IMAGE = '/images/info-section.png',
  PLUS_ICON = '/images/plus-icon.png',
  MINUS_ICON = '/images/minus-icon.png',
  BAG_ICON = '/images/bag-icon.png',
  CHECK_ICON = '/images/icon-check.png',
  ICON_STAR = '/images/icon-star.png',
  ICON_STICK = '/images/icon-stick.png',
  ICON_DOUBLE = '/images/icon-double.png',
}
